<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (Schema::hasColumn('team_messages', 'client_uuid')) {
            return;
        }

        Schema::table('team_messages', function (Blueprint $table) {
            // One id per compose attempt, generated by the chat client. A double Enter or a
            // retry after "Send timed out" re-sends the same id, and the server returns the
            // message it already saved instead of creating a duplicate. Null for old rows.
            $table->string('client_uuid', 64)->nullable()->after('sender_id');
            $table->unique(['sender_id', 'client_uuid'], 'team_messages_sender_client_uuid_unique');
        });
    }

    public function down(): void
    {
        if (! Schema::hasColumn('team_messages', 'client_uuid')) {
            return;
        }

        Schema::table('team_messages', function (Blueprint $table) {
            $table->dropUnique('team_messages_sender_client_uuid_unique');
            $table->dropColumn('client_uuid');
        });
    }
};
